export const fakeProducts = [
	{
		image: 'https://mihome.uz/wp-content/uploads/2024/04/6212.jpg.webp',
		title: 'A comfortable ',
		distance: '1 km',
		time: '10 min',
		address: 'Toshkent, Yunusobod 12',
		price: '$ 10000',
		likes: 3,
	},
	{
		image: 'https://mihome.uz/wp-content/uploads/2024/04/6212.jpg.webp',
		title: 'A comfortable two-room apartment with..',
		distance: '2 km',
		time: '20 min',
		address: 'Toshkent, Shayxontoxir 12',
		price: '$ 20000',
		likes: 5,
	},
	{
		image: 'https://mihome.uz/wp-content/uploads/2024/04/6212.jpg.webp',
		title: 'A comfortable two-room apartment with..',
		distance: '3 km',
		time: '30 min',
		address: 'Toshkent, Mirzo Ulugbek 12',
		price: '$ 30000',
		likes: 7,
	},
	{
		image: 'https://mihome.uz/wp-content/uploads/2024/04/6212.jpg.webp',
		title: 'A comfortable two-room apartment with.. ',
		distance: '1 km',
		time: '10 min',
		address: 'Toshkent, Yunusobod 12',
		price: '$ 10000',
		likes: 3,
	},
	{
		image: 'https://mihome.uz/wp-content/uploads/2024/04/6212.jpg.webp',
		title: 'A comfortable two-room apartment with..',
		distance: '2 km',
		time: '20 min',
		address: 'Toshkent, Shayxontoxir 12',
		price: '$ 20000',
		likes: 5,
	},
	{
		image: 'https://mihome.uz/wp-content/uploads/2024/04/6212.jpg.webp',
		title: 'A comfortable two-room apartment with..',
		distance: '3 km',
		time: '30 min',
		address: 'Toshkent, Mirzo Ulugbek 12',
		price: '$ 30000',
		likes: 7,
	},
]
